### ISSUE TITLE
remote_debugger.py bug: Preferences pane's filepath input fields fail to appear on Blender 2.93.x

### ISSUE THREAD

**Issue by ZeroGravitasIndeed** [sybrenstuvel/random-blender-addons#7] opened 2021-07-22 20:37 UTC
_(This bug shows up on fresh installations of Blender 2.93.0 and 2.93.1 on both Windows 10 and macOS 10.14.6 Mojave, with the "Developer's Extras" checkbox both ticked and unticked. The add-on works correctly on Blender 2.92.x)_

After installing the add-on and ticking the activation checkbox, the add-on shows its Preferences pane, but the filepath fields, buttons and labels for locating the pydevd.py and Pycharm egg files aren't displayed. The "Preferences" and "Make sure you select…" texts do appear, though.

![remote_debugger py-bug](https://user-images.githubusercontent.com/70643459/126705799-3b88cc1f-3615-4650-8e60-0847f9975882.png)

**Comment by mk-relax** [comment] 2021-08-04 20:18
Ran into the same problem.

This is caused by the `convert_properties` decorator not working anymore because the non-annotated properties `eggpath` and `pydevpath` are now of a new type: `_PropertyDeferred`. 

Personally, I temporarily fixed it by changing the properties to annotations (e.g. `eggpath: StringProperty` instead of `eggpath = StringProperty` and removing the decorator altogether. But thats not backwards compatible for < 2.80.

**Comment by sybrenstuvel** [comment] 2021-08-05 17:24
@mk-relax could you share that version as a pull request? I think by now it's fine to have the add-on for 2.80+ Blenders only.

**Comment by VictorAtPL** [comment] 2021-09-16 13:52
Because tip from @mk-relax wasn't obvious for me, I will try to rephrase what he suggests to do.

Change `eggpath = StringProperty(` to `eggpath : StringProperty(` and `pydevpath = StringProperty(` to `pydevpath : StringProperty(`.

**Comment by VictorAtPL** [comment] 2021-09-16 14:05
But even with this change, "debugger" is not shown in search menu (`F3`).

**Comment by be-glass** [comment] 2021-09-16 14:43
You need to activate developer extras in the preferences: Edit > Preferences > Interface > Developer Extras

**Comment by be-glass** [comment] 2021-09-16 14:46
I forked and implemented mk-relax' change, and it works as expected. I also created a pull request for Sybren.

**Comment by VictorAtPL** [comment] 2021-09-16 14:56
@be-glass 
You're right. Enabling Developer Extras helped. :-)

**Comment by sybrenstuvel** [comment] 2024-10-17 17:47
I'm not developing this add-on any more, haven't used it myself for years. I'll close this issue.

**Closed by sybrenstuvel** 2024-10-17 17:47 UTC
